Repository freedomofpress/securedrop-workstation, pull requests merged in 2020-02, with the labels that each got.

#432 Begins dynamic dev/prod config logic
  MANIFEST.in
  Makefile
  README.md
  VERSION
  config.json.example
  dom0/fpf-apt-test-repo.sls
  dom0/sd-clean-all.sls
  dom0/sd-default-config.sls
  dom0/sd-default-config.yml
  dom0/sd-dom0-files.sls
  dom0/sd-sys-firewall-files.sls
  rpm-build/SPECS/securedrop-workstation-dom0-config.spec
  scripts/configure-environment
  scripts/securedrop-admin.py
  scripts/validate_config.py
  sd-workstation/securedrop-release-signing-pubkey.asc
  sys-firewall/sd-copy-rpm-repo-pubkey.sh
  tests/test_dom0_rpm_repo.py
  tests/test_sys_firewall.py
  tests/test_vms_platform.py
Labels: release blocker

#448 Clarify dev/staging/prod status in docs; small tweaks
  README.md
Labels: docs, small off-sprint PR

#452 Enforce code formatting in CI for Updater
  .circleci/config.yml
  launcher/Makefile
  launcher/sdw_updater_gui/Updater.py
  launcher/test-requirements.in
  launcher/test-requirements.txt
Labels: small off-sprint PR

#439 Update `make template` target to use SecureDrop release signing key
  Makefile
  README.md
  builder/build-workstation-template
Labels: release blocker

#450 Skips running the updater if last update was good, a reboot isn't needed, and a config-specified delta isn't defined.
  VERSION
  launcher/sdw-launcher.py
  launcher/sdw_updater_gui/Updater.py
  launcher/sdw_updater_gui/UpdaterApp.py
  launcher/tests/test_updater.py
  rpm-build/SPECS/securedrop-workstation-dom0-config.spec
Labels: release blocker

#458 Apply dom0 state as part of updater
  launcher/sdw_updater_gui/Updater.py
  launcher/sdw_updater_gui/UpdaterApp.py
  launcher/tests/test_updater.py
Labels: release blocker

#430 Remove legacy updater
  MANIFEST.in
  README.md
  VERSION
  dom0/sd-clean-all.sls
  dom0/sd-dom0-files.sls
  dom0/securedrop-update
  rpm-build/SPECS/securedrop-workstation-dom0-config.spec
  setup.py
Labels: release blocker

#461 Tweaks to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, small off-sprint PR

#454 Detect process conflicts with sdw-notify
  launcher/sdw-notify.py
  launcher/sdw_notify/Notify.py
  launcher/sdw_util/Util.py
  launcher/tests/test_util.py
Labels: small off-sprint PR

#468 Fix initial beta release docs and manifest, update version to 0.2.1
  MANIFEST.in
  Makefile
  README.md
  VERSION
  rpm-build/SPECS/securedrop-workstation-dom0-config.spec
Labels: small off-sprint PR

#465 Write `sdw-last-updated` after upgrades in REBOOT_REQUIRED case
  launcher/sdw_updater_gui/UpdaterApp.py
Labels: release blocker
