Repository freedomofpress/securedrop-workstation, pull requests merged in 2024-05, with the labels that each got.

#1025 Stop using assert in validate_config.py
  files/validate_config.py
Labels: good first issue

#1027 Functional RPC policy tests
  tests/test_qubes_rpc.py
Labels: good first issue

#1028 Configure ruff
  Makefile
  dom0/remove-tags.py
  files/destroy-vm.py
  files/sdw-admin.py
  files/sdw-login.py
  files/sdw-notify.py
  files/validate_config.py
  launcher/tests/conftest.py
  launcher/tests/test_notify.py
  launcher/tests/test_updater.py
  launcher/tests/test_util.py
  poetry.lock
  pyproject.toml
  scripts/configure-environment.py
  scripts/fake-setarch.py
  sdw_notify/Notify.py
  sdw_notify/NotifyApp.py
  sdw_updater/Updater.py
  sdw_updater/UpdaterApp.py
  sdw_updater/UpdaterAppUiQt5.py
  sdw_util/Util.py
  setup.py
  tests/base.py
  tests/test_app.py
  tests/test_dom0_rpm_repo.py
  tests/test_gpg.py
  tests/test_log_vm.py
  tests/test_proxy_vm.py
  tests/test_qubes_rpc.py
  tests/test_qubes_vms.py
  tests/test_sd_devices.py
  tests/test_sd_whonix.py
  tests/test_sys_usb.py
  tests/test_viewer.py
  tests/test_vms_exist.py
  tests/test_vms_platform.py
Labels: good first issue

#840 Rely on systemd services for securedrop-log's provisioning
  dom0/sd-gpg.sls
  dom0/sd-log.sls
  dom0/sd-logging-setup.sls
  dom0/sd-rsyslog.conf.j2
  dom0/sd-workstation.top
  files/provision-all
  tests/base.py
  tests/test_gpg.py
  tests/test_log_vm.py
  tests/test_vms_exist.py
Labels: provisioning, salt

#1023 Initial Qubes 4.2 Updater Integration
  launcher/tests/test_updater.py
  launcher/tests/test_updaterapp.py
  sdw_updater/Updater.py
  sdw_updater/UpdaterApp.py
Labels: sprint goal

#1054 Set skip_if_unavailable=False in .repo file
  dom0/sd-dom0-files.sls
  tests/test_dom0_rpm_repo.py
Labels: sprint goal
