Repository freedomofpress/securedrop-workstation, pull requests merged in 2024-06, with the labels that each got.

#1043 Removes MIME overrides out of salt and sd-proxy disposable
  Makefile
  securedrop_salt/sd-app.sls
  securedrop_salt/sd-devices.sls
  securedrop_salt/sd-mime-handling.sls
  securedrop_salt/sd-proxy.sls
  securedrop_salt/sd-viewer.sls
  securedrop_salt/sd-workstation.top
  securedrop_salt/securedrop-handle-upgrade
  tests/base.py
  tests/test_app.py
  tests/test_proxy_vm.py
  tests/test_sd_devices.py
  tests/test_viewer.py
  tests/test_vms_exist.py
  tests/test_vms_platform.py
Labels: sprint goal

#857 Make our VMs internal, hiding their applications from the menu
  securedrop_salt/sd-app.sls
  securedrop_salt/sd-gpg.sls
  securedrop_salt/sd-log.sls
  securedrop_salt/sd-proxy.sls
  securedrop_salt/sd-viewer.sls
Labels: UX

#1064 Improve error handling in validation_config.py
  files/validate_config.py
Labels: 4.2 qa period

#1068 Add VM test asserting no default_dispvm in sd-proxy and sd-proxy-dvm
  tests/test_vms_exist.py
Labels: 4.2 qa period

#1082 Test desired state of Linux Security Module configuration
  tests/base.py
  tests/test_app.py
  tests/test_proxy_vm.py
  tests/test_sys_usb.py
  tests/test_viewer.py
Labels: 4.2 qa period

#1084 Explicitly set default_dispvm on all VMs we manage
  securedrop_salt/sd-app.sls
  securedrop_salt/sd-base-template.sls
  securedrop_salt/sd-devices.sls
  securedrop_salt/sd-gpg.sls
  securedrop_salt/sd-log.sls
  securedrop_salt/sd-viewer.sls
  securedrop_salt/sd-whonix.sls
  securedrop_salt/sd-workstation-template.sls
  tests/test_vms_exist.py
Labels: 4.2 qa period

#1085 Improve sd-gpg test
  tests/test_gpg.py
Labels: 4.2 qa period

#1095 Ensure outdated templates are removed
  tests/base.py
  tests/test_viewer.py
  tests/test_vms_exist.py
  tests/test_vms_platform.py
Labels: 4.2 qa period

#1098 Make sd-viewer and sd-app internal (again)
  securedrop_salt/sd-app.sls
  securedrop_salt/sd-viewer.sls
  tests/test_vms_exist.py
Labels: 4.2 qa period
